# Generated by Django 4.0.5 on 2022-08-09 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NightOutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdNightOuts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('nightOut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='nightout.nightoutmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'nightOut')},
            },
        ),
        migrations.CreateModel(
            name='ParticipantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.BooleanField(default=False)),
                ('nightOut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantDates', to='nightout.nightoutmodel')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantDates', to='nightout.participant')),
                ('suggestedDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestedDates', to='nightout.datesuggestion')),
            ],
        ),
        migrations.AddField(
            model_name='datesuggestion',
            name='nightOut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestedDates', to='nightout.nightoutmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='datesuggestion',
            unique_together={('nightOut', 'date')},
        ),
    ]
