# Generated by Django 4.0.5 on 2022-12-16 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NightOutModel',
            fields=[
                ('title', models.CharField(max_length=40)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('finalDate', models.DateTimeField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('datePhase', 'Date Phase'), ('planningPhase', 'Planning Phase'), ('votingPhase', 'Voting Phase'), ('finished', 'Finished')], default='datePhase', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdNightOuts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('nightOut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='nightout.nightoutmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'nightOut')},
            },
        ),
        migrations.CreateModel(
            name='PlanSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planSuggestions', to='nightout.participant')),
                ('nightOut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planSuggestions', to='nightout.nightoutmodel')),
            ],
            options={
                'ordering': ['creator'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votedSuggestions', to='nightout.participant')),
                ('planSuggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='nightout.plansuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('rating', models.FloatField(default=0)),
                ('photoKey', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=60)),
                ('locationType', models.CharField(max_length=90)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('planSuggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planEntries', to='nightout.plansuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.BooleanField(default=False)),
                ('nightOut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantDates', to='nightout.nightoutmodel')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantDates', to='nightout.participant')),
                ('suggestedDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestedDates', to='nightout.datesuggestion')),
            ],
            options={
                'ordering': ['participant'],
            },
        ),
        migrations.AddField(
            model_name='nightoutmodel',
            name='finalFirstSuggestion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thisNightOutFirst', to='nightout.plansuggestion'),
        ),
        migrations.AddField(
            model_name='nightoutmodel',
            name='finalSecondSuggestion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thisNightOutSecond', to='nightout.plansuggestion'),
        ),
        migrations.AddField(
            model_name='datesuggestion',
            name='nightOut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestedDates', to='nightout.nightoutmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='datesuggestion',
            unique_together={('nightOut', 'date')},
        ),
    ]
