# Generated by Django 4.0.5 on 2022-08-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantdate',
            options={'ordering': ['participant']},
        ),
    ]
