# Generated by Django 4.0.5 on 2023-01-05 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightoutmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
