# Generated by Django 4.0.5 on 2022-08-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0002_alter_participantdate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightoutmodel',
            name='phase',
            field=models.CharField(choices=[('datePhase', 'Date Phase'), ('votingPhase', 'Voting Phase'), ('finished', 'Finished')], default='datePhase', max_length=20),
        ),
    ]
