# Generated by Django 4.0.5 on 2023-01-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0002_alter_nightoutmodel_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datesuggestion',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='datesuggestion',
            unique_together=set(),
        ),
    ]
