# Generated by Django 4.0.5 on 2023-01-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0003_alter_datesuggestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datesuggestion',
            options={'ordering': ['date']},
        ),
    ]
