# Generated by Django 4.0.5 on 2022-08-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0003_nightoutmodel_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nightoutmodel',
            old_name='startTime',
            new_name='finalDate',
        ),
    ]
