# Generated by Django 4.0.5 on 2023-01-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0004_alter_datesuggestion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantdate',
            options={'ordering': ['suggestedDate']},
        ),
    ]
