# Generated by Django 4.0.5 on 2022-08-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0004_rename_starttime_nightoutmodel_finaldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightoutmodel',
            name='phase',
            field=models.CharField(choices=[('datePhase', 'Date Phase'), ('planningPhase', 'Planning Phase'), ('votingPhase', 'Voting Phase'), ('finished', 'Finished')], default='datePhase', max_length=20),
        ),
    ]
