# Generated by Django 4.0.5 on 2022-08-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0005_alter_nightoutmodel_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='planSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nightOut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planSuggestions', to='nightout.nightoutmodel')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planSuggestions', to='nightout.participant')),
            ],
            options={
                'ordering': ['participant'],
            },
        ),
        migrations.CreateModel(
            name='planEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=60)),
                ('locationType', models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('outdoor', 'Outdoors'), ('sports', 'Sports'), ('club', 'Club'), ('other', 'Other')], default='restaurant', max_length=20)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('planSuggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planEntries', to='nightout.plansuggestion')),
            ],
        ),
    ]
