# Generated by Django 4.0.5 on 2023-01-13 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nightout', '0005_alter_participantdate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('notificationType', models.CharField(choices=[('default', 'default'), ('ask for next Phase', 'asks you to bring the Nightout to the next Phase.'), ('nightout finished', 'This Nightout is finished, go take a look'), ('next Phase', 'This Nightout is in the next phase')], max_length=40)),
                ('nightout', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationsOnNightout', to='nightout.nightoutmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedNotifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
