# Generated by Django 4.0.5 on 2022-08-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0006_plansuggestion_planentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planentry',
            name='description',
        ),
        migrations.AddField(
            model_name='planentry',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='planentry',
            name='photoKey',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='planentry',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plansuggestion',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
