# Generated by Django 4.0.5 on 2023-01-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notificationType',
            field=models.CharField(choices=[('default', 'default'), ('ask for next Phase', 'asks you to bring the Nightout to the next Phase.'), ('nightout finished', 'This Nightout is finished, go take a look'), ('next Phase', 'This Nightout is in the next phase')], max_length=40, null=True),
        ),
    ]
