# Generated by Django 4.0.5 on 2023-01-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0007_alter_notification_notificationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='nightout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationsOnNightout', to='nightout.nightoutmodel'),
        ),
    ]
