# Generated by Django 4.0.5 on 2022-08-22 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0007_remove_planentry_description_planentry_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansuggestion',
            name='nightOut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlanSuggestions', to='nightout.nightoutmodel'),
        ),
        migrations.AlterField(
            model_name='plansuggestion',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlanSuggestions', to='nightout.participant'),
        ),
    ]
