# Generated by Django 4.0.5 on 2022-08-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0008_alter_plansuggestion_nightout_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plansuggestion',
            options={'ordering': ['creator']},
        ),
        migrations.RenameField(
            model_name='plansuggestion',
            old_name='participant',
            new_name='creator',
        ),
    ]
