# Generated by Django 4.0.5 on 2022-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0009_alter_plansuggestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planentry',
            name='locationType',
            field=models.CharField(max_length=20),
        ),
    ]
