# Generated by Django 4.0.5 on 2023-01-16 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nightout', '0009_notificationmodel_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sentNotifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
