# Generated by Django 4.0.5 on 2023-01-17 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nightout', '0010_notificationmodel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentNotifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
