# Generated by Django 4.0.5 on 2022-10-31 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0011_alter_planentry_locationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansuggestion',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planSuggestions', to='nightout.participant'),
        ),
        migrations.AlterField(
            model_name='plansuggestion',
            name='nightOut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planSuggestions', to='nightout.nightoutmodel'),
        ),
    ]
