# Generated by Django 4.0.5 on 2022-11-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0012_alter_plansuggestion_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votedSuggestions', to='nightout.participant')),
                ('planSuggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='nightout.plansuggestion')),
            ],
        ),
    ]
