# Generated by Django 4.0.5 on 2023-01-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0012_alter_notificationmodel_notificationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='nightout',
            field=models.ForeignKey(default='b5dba0d1-29e6-4405-bf21-4fce490a03fa', on_delete=django.db.models.deletion.CASCADE, related_name='notificationsOnNightout', to='nightout.nightoutmodel'),
            preserve_default=False,
        ),
    ]
