# Generated by Django 4.0.5 on 2023-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0013_alter_notificationmodel_nightout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='notificationMessage',
            field=models.CharField(choices=[('ask_next_phase', 'asks you to bring this Nightout to the next phase'), ('nightout_finished', 'This Nightout is finished. Go take a look'), ('added_you_to_nightout', 'has addded you to a Nightout')], max_length=80),
        ),
    ]
