# Generated by Django 4.0.5 on 2023-01-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0014_alter_notificationmodel_notificationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansuggestion',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
