# Generated by Django 4.0.5 on 2022-11-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0014_rename_participant_suggestionvote_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightoutmodel',
            name='finalSuggestion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nightout.plansuggestion'),
        ),
    ]
