# Generated by Django 4.0.5 on 2022-11-19 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0015_nightoutmodel_finalsuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nightoutmodel',
            name='finalSuggestion',
        ),
        migrations.AddField(
            model_name='nightoutmodel',
            name='finalFirstSuggestion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thisNightOutFirst', to='nightout.plansuggestion'),
        ),
        migrations.AddField(
            model_name='nightoutmodel',
            name='finalSecondSuggestion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thisNightOutSecond', to='nightout.plansuggestion'),
        ),
    ]
