# Generated by Django 4.0.5 on 2023-02-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0018_planentry_formtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planentry',
            name='locationType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
