# Generated by Django 4.0.5 on 2023-02-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0019_alter_planentry_locationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuggestion',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
