# Generated by Django 4.0.5 on 2023-02-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0021_alter_planentry_options_remove_plansuggestion_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='abstention',
            field=models.BooleanField(default=False),
        ),
    ]
