# Generated by Django 4.0.5 on 2023-02-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightout', '0023_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AddField(
            model_name='nightoutmodel',
            name='joinLinkCreated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nightoutmodel',
            name='joinLinkPassword',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
