# Generated by Django 4.0.5 on 2023-02-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarStyle',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('adventurer', 'adventurer'), ('avataaars', 'avataaars'), ('big-ears', 'big-ears'), ('miniavs', 'miniavs'), ('open-peeps', 'open-peeps'), ('pixel-art', 'pixel-art'), ('personas', 'personas')], default='pixel-art', max_length=40),
        ),
    ]
